name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"       # Daily at 18:00 UTC (03:00 JST)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contributions
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ambideXtrous9

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A .
          if git commit -m "Update 3D contrib SVG"; then
            git push
          fi
