name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3
        with:
          ref: main  # checkout main branch to commit snake SVGs there

      - name: Generate GitHub Contribution Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ambideXtrous9
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Move output to specific folder
        run: |
          mkdir -p snake
          cp dist/*.svg snake/

      - name: Commit and push changes to main branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snake/*.svg
          git commit -m "Update GitHub contribution snake SVGs" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
